name: CI
on: [push]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: goal_dashboard
          POSTGRES_DB: goal_dashboard_test
          POSTGRES_PASSWORD: 'BAET&Hs%3qdB2vEZ]>2fwwEiPz(tiH22hJRo@Xmakbr7RpURVox&QyUUWpj?K72A'
        ports: ['5432:5432']
    env:
      RAILS_ENV: test
      PGHOST: localhost
      PGUSER: goal_dashboard
      PGPASSWORD: 'BAET&Hs%3qdB2vEZ]>2fwwEiPz(tiH22hJRo@Xmakbr7RpURVox&QyUUWpj?K72A'
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --pure-lockfile
      - run: yarn run prettier --check .

      - run: bundle exec rails db:setup
      - run: bundle exec rspec
